### ISSUE TITLE
Must pass MODE_NO_SSL_VERIFY as of 1.6.3

### ISSUE THREAD

**Issue by rubyjedi** [NationalAssociationOfRealtors/libRETS#84]
As a result of commit 7baa4b8, I notice my client code is now required to pass MODE_NO_SSL_VERIFY in order to continue logging into MLS repositories as had been done with LibRETS 1.6.2.

This is because there is a hard-coded **cacert.pem** file declared, but not present on my (Linux, not Windows) systems:

```* Expire in 50 ms for 1 (transfer 0x561ae5af66a0)
*   Trying xxx.xxx.xxx.xxx...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x561ae5af66a0)
* Connected to xxxx.xxxx.com (xxx.xxx.xxx.xxx) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* error setting certificate verify locations:
  CAfile: cacert.pem
  CApath: none
* Closing connection 0
```
Am I misunderstanding the intent of this change? Seems like an error to hard-code a local pem file, when most of the certificates on a typical machine would reside in /etc/pki, no?

**Comment by vitorcortes** [comment]
Hi there,

Are there any plans to fix this issue? I’m currently working on a client solution, but I have noticed that I can only  receive data back from the server if the SSL verification is turned off, like it has been previously reported. Otherwise, if fails to authenticate. 

I’m providing the details of the error below:

**Error message**: “Could not get URL [xxxx] - HTTP response code: 503”

It only works when I add the following:  **this.Session.SetModeFlags(RetsSession.MODE_NO_SSL_VERIFY);** 

Thanks

**Comment by zBestData** [comment]
There is a version 1.6.3 still in beta that worked for me.  Details at 
http://blog.zbestdata.com/post/2019/08/19/libRETS-stops-pulling-mls-data-and-login-fails

There is also this project that I don't think is being supported anymore.  I fixed many of the issues and attached the fixed version at the bottom of this thread.  I plan to go back and fix more when I have the time
https://github.com/CrestApps/RetsConnector/issues/3

**Comment by vitorcortes** [comment]
> There is a version 1.6.3 still in beta that worked for me. Details at
> http://blog.zbestdata.com/post/2019/08/19/libRETS-stops-pulling-mls-data-and-login-fails
> 
> There is also this project that I don't think is being supported anymore. I fixed many of the issues and attached the fixed version at the bottom of this thread. I plan to go back and fix more when I have the time
> [CrestApps/RetsConnector#3](https://github.com/CrestApps/RetsConnector/issues/3)

Hi @zBestData, thanks for the reply! But unfortunately I'm still getting the same error, even after I installed the beta. Without **this.Session.SetModeFlags(RetsSession.MODE_NO_SSL_VERIFY);**, it can't authenticate. I know it's a libRETS issue because I'm able to authenticate by testing it through the RetsConnector app. 

Is there anything else you did, besides just calling **this.Session.Login(userName, password)**?

**Comment by rubyjedi** [comment]
For the time being, I've resorted to compiling this code at version 1.6.2 until commit 7baa4b8 by @jbramleycl has been reviewed or reversed by project owners.

That looks like some windows-specific band-aid fix that (IMHO) doesn't belong in a cross-platform library without a platform-test as a guard.

**Comment by zBestData** [comment]
@vitorcortes    

I have 3 data providers that I have to use MODE_NO_SSL_VERIFY for:  NavicaMLS, Matrix, and Property Information Network.   Try setting it using it numerical value.  It should be 8.  I am loading the config from a centralized database config.  My coded is below.  

I also noticed that upgraded the beta version to full release.

            retsSession = new RetsSession(account.LoginURL.Trim());
            if (provider.RETS_Mode > 0)
            {
                retsSession.SetModeFlags((uint)provider.RETS_Mode);
            }

            if (!string.IsNullOrEmpty(account.UserAgent.ToSafeString()))
            {
                retsSession.SetUserAgent(account.UserAgent.ToSafeString());
                retsSession.SetUserAgentPassword(account.UserAgentPassword.ToSafeString());
            }

               //Log in to RETS
                bool loginResult = retsSession.Login(account.UserName.ToSafeString(), account.Password.ToSafeString());

                if (!loginResult)
                {
                    Console.WriteLine("\nLogin to RETS Failed at " + DateTime.Now);
                }

**Comment by jbramleycl** [comment]
I definitely regret leaving a hard-coded reference to cacert.pem in that change, and the code was added to address a deficiency in how cURL is compiled on Windows (without SChannel support), but it just provides an ability to pass another option to cURL.

**Comment by vitorcortes** [comment]
> @vitorcortes
> 
> I have 3 data providers that I have to use MODE_NO_SSL_VERIFY for: NavicaMLS, Matrix, and Property Information Network. Try setting it using it numerical value. It should be 8. I am loading the config from a centralized database config. My coded is below.
> 
> I also noticed that upgraded the beta version to full release.
> 
> ```
>         retsSession = new RetsSession(account.LoginURL.Trim());
>         if (provider.RETS_Mode > 0)
>         {
>             retsSession.SetModeFlags((uint)provider.RETS_Mode);
>         }
> 
>         if (!string.IsNullOrEmpty(account.UserAgent.ToSafeString()))
>         {
>             retsSession.SetUserAgent(account.UserAgent.ToSafeString());
>             retsSession.SetUserAgentPassword(account.UserAgentPassword.ToSafeString());
>         }
> 
>            //Log in to RETS
>             bool loginResult = retsSession.Login(account.UserName.ToSafeString(), account.Password.ToSafeString());
> 
>             if (loginResult)
>             {
>                 //import data
>             }
> ```

Thanks @zBestData! My solution was to actually implement my own SSL verification method, before doing any requests to the RETS Server. Since in my case the data coming through was still encrypted, all I had to do was to verify the SSL certificate myself. ;)

**Comment by jazzklein** [comment]
You can also provide a `cacert.pem` file with the trust chain `SetCACertPath(std::string cacert_path)`.

**Comment by rubyjedi** [comment]
Wait.. so you're going to accept a change that breaks functionality on Non-Windows platforms?

Everything was working fine prior to this change; and if anything, there should be a platform-specific guard since this is a Windows-specific fix.

**Comment by jazzklein** [comment]
Take a look at the code. This was what was there:
```
    curlEasy->SetCAInfo("cacert.pem");
```
It is now:
```
    curlEasy->SetCAInfo(mCACertPath);
```
and 
```
    mCACertPath = "cacert.pem";
```
and this is the new API:
```
    /**
     * Set the path to the CACert.pem file
     * @param A string containing the path to cacert.pem
     */
    virtual void SetCACertPath(std::string cacert_path) {mCACertPath = cacert_path;}
```
Old functionality is preserved and everyone benefits.

**Comment by rubyjedi** [comment]
All that change did was move out the hard-coded cert-file name.

The old functionality made no explicit call to `curlEasy->SetCAInfo("cacert.pem")`, and left it to curlEasy to auto-resolve the CA folder through the normal mechanisms. The introduced functionality linked-to at the top of this Issue works around that folder-resolution breakage, which only exists on Windows platforms.

Sad to say, the code that's in 1.6.5 is still functionally equivalent (i.e. introduced breakage on non-Windows platforms); and I'd still suggest adding a platform-testing conditional for Windows before calling **setCACertPath()**

**Comment by jazzklein** [comment]
> All that change did was move out the hard-coded cert-file name.

Exactly, and replaced it by an API that allows you to control the path. The variable now contains the same default name that was there. So if the new API is not called, the same default exists.

> 
> The old functionality made no explicit call to `curlEasy->SetCAInfo("cacert.pem")`, and left it to curlEasy to auto-resolve the CA folder through the normal mechanisms. The introduced functionality linked-to at the top of this Issue works around that folder-resolution breakage, which only exists on Windows platforms.

Sorry, it's not just a Windows problem. While it may have originally worked on your system, there are systems where the default path to the root certificates _is not_  `/etc/ssl/certs`. In fact, here are just a few of the other possibilities:
```
/etc/ssl/certs/ca-certificates.crt             // Debian/Ubuntu/Gentoo etc.
/etc/pki/tls/certs/ca-bundle.crt               // Fedora/RHEL 6
/etc/ssl/ca-bundle.pem                           // OpenSUSE
/etc/pki/tls/cacert.pem                            // OpenELEC
/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem // CentOS/RHEL 7
/etc/ssl/cert.pem                                     // Alpine Linux, FreeBSD
```

Therefore, it is broken for anyone _not_ using your operating system. I use FreeBSD and OS/X, and it is broken there. And, in fact, since we are building from source, and since one can build `cURL` and use the `--with-ca-bundle` option to point it anywhere, we really need some means of telling `cURL` where we want it to look.

While the original author of the fix may have been trying to address a Windows issue, it is the right idea for all platforms. This fix allows you to handle all instances, at the cost that you will have to add one more API call during your initialization to set that location. It's been broken for a while, so you've already worked around it on your platform.

**Comment by rubyjedi** [comment]
Not quite, but whatever.. if this is deemed the permanent resolution then so be it.

The original mechanism wasn't broken in LibRETS per se, but is broken for anyone whose platform is operating a broken installation of libcurl.

if `curl-config --ca`  on a platform returns a flawed result, then yes, this new mechanism would be necessary. 

Everyone else who has a properly configured libcurl is now penalized by this "fix" forcing a method-call pointing to an incorrect hard-coded location -- forcing users who had working libcurl behavior to now hard-code a location in their client code to override the bogus value hard-coded in this release.

CentOS 7:  /etc/pki/tls/certs/ca-bundle.crt
Fedora 31:  /etc/pki/tls/certs/ca-bundle.crt
Alpine Linux 3.11:  /etc/ssl/certs/ca-certificates.crt

I also compile from source -- including compiling Swig 4.0.2 from source -- into a Docker container for use with Node11/Typescript. While it's a minor nuisance, it's just as well to monkey-patch libRETS in the container-build scripts to restore original unadulterated behavior.

I appreciate you and your team's efforts on addressing this, but I respectfully disagree on the mechanics of the solution.
